<a href="https://colab.research.google.com/github/thnahphung/ML/blob/main/Lab_1_20130099_DuongThanhPhung.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Task 1.1. Develop a Python program to perform the following tasks:
– Input an integer number n.
– Input n integer numbers x1, x2,..., xn and append them into a list L.
– Find the max/min element in L.
– Compute the sum of elements in L.
– Sort the list L in ascending order.
– Show how many positive and negative numbers are in the list L.

In [ ]:
def fun(listNum):
    positive = 0
    negative = 0
    zero = 0
    for num in listNum:
        if num < 0:
            positive += 1
        elif num > 0:
            negative += 1
        else:
            zero += 1
    return positive, negative, zero


n = int(input('n: '))
listNum = []
for i in range(n):
    listNum.append(int(input('n' + str(i) + ': ')))

print(listNum)
print('max: ', max(listNum))
print('min: ', min(listNum))
print('sum: ', sum(listNum))
print('sort: ', sorted(listNum))

positive, negative, zero = fun(listNum)
print('positive: ', positive)
print('negative: ', negative)
print('zero: ', zero)


n: 5
n0: -1
n1: 134
n2: -12
n3: 543
n4: 0
[-1, 134, -12, 543, 0]
max:  543
min:  -12
sum:  664
sort:  [-12, -1, 0, 134, 543]
positive:  2
negative:  2
zero:  1


Task 1.2. Develop a Python program to compute Sn as follows:

In [ ]:
def Sn(n):
    sn = 0
    for i in range(n):
        sn += 1 / (2 * i + 1)
    return sn

n = int(input("n: "))
print(Sn(n))

n: 3
1.5333333333333332


Task 1.3. For a given class diagram as follows:

In [9]:
from abc import ABC, abstractmethod
from datetime import date


class Order:
    def __init__(self, ids, customer, employee, date, items):
        self.__ids = ids
        self.__customer = customer
        self.__employee = employee
        self.__date = date
        self.__items = items

    @property
    def ids(self):
        return self.__ids

    @ids.setter
    def ids(self, value):
        self.__ids = value

    @property
    def customer(self):
        return self.__customer

    @customer.setter
    def customer(self, value):
        self.__customer = value

    @property
    def employee(self):
        return self.__employee

    @employee.setter
    def employee(self, value):
        self.__employee = value

    @property
    def date(self):
        return self.__date

    @date.setter
    def date(self, value):
        self.__date = value

    @property
    def items(self):
        return self.__items

    @items.setter
    def items(self, value):
        self.__items = value

    def __repr__(self):
        return str(self.__ids) + " " + self.__customer

    def getListProductInOrder(self):
        result = []
        for item in self.__items:
            result.append(item.item)
        return result

    def getProductHighestPriceInOder(self):
        return max(self.getListProductInOrder(), key=lambda item: item.price)

    def showNumberOfProducts(self):
        counts = dict()
        for oderItem in self.__items:
            counts[oderItem.item] = counts.get(oderItem.item, 0) + oderItem.amount
        return counts


class OrderItem:
    def __init__(self, item, amount):
        self.__item = item
        self.__amount = amount

    @property
    def item(self):
        return self.__item

    @item.setter
    def item(self, value):
        self.__item = value

    @property
    def amount(self):
        return self.__amount

    @amount.setter
    def amount(self, value):
        self.__amount = value

    def __repr__(self):
        return str(self.__item) + " " + str(self.__amount)


class OrderManager:
    def __init__(self, orders):
        self.__orders = orders

    @property
    def orders(self):
        return self.__orders

    @orders.setter
    def orders(self, value):
        self.__orders = value

    def __repr__(self):
        return self.__orders

    def getListProductHighestPriceInAOder(self):
        result = []
        for item in self.__orders:
            result.append(item.getProductHighestPriceInOder())
        return result

    def getProductHighestPriceInOders(self):
        return max(self.getListProductHighestPriceInAOder(), key=lambda item: item.price)

    def showNumberOfProducts(self):
        counts = dict()
        for oder in self.__orders:
            for product, amount in oder.showNumberOfProducts().items():
                counts[product] = counts.get(product, 0) + amount
        return counts


class Product(ABC):
    def __init__(self, name, kind, price, expiredDate):
        self._name = name
        self._kind = kind
        self._price = price
        self._expiredDate = expiredDate

    @property
    def name(self):
        return self._name

    @name.setter
    def name(self, value):
        self._name = value

    @property
    def kind(self):
        return self._kind

    @kind.setter
    def kind(self, value):
        self._kind = value

    @property
    def price(self):
        return self._price

    @price.setter
    def price(self, value):
        self._price = value

    @property
    def expiredDate(self):
        return self._expiredDate

    @expiredDate.setter
    def expiredDate(self, value):
        self._expiredDate = value

    def __repr__(self):
        return self.name + " " + str(self._price)


class ImportedProduct(Product):
    def __init__(self, name, kind, price, expiredDate, fromCountry):
        super().__init__(name, kind, price, expiredDate)
        self.__fromCountry = fromCountry

    @property
    def fromCountry(self):
        return self.__fromCountry

    @fromCountry.setter
    def fromCountry(self, value):
        self.__fromCountry = value

    def __repr__(self):
        return self.name + " " + str(self._price) + ' ' + self.fromCountry


class DomesticProduct(Product):
    def __init__(self, name, kind, price, expiredDate):
        super().__init__(name, kind, price, expiredDate)


d = date(2002, 10, 19)
p1 = ImportedProduct("Xoai", "Trai Cay", 10000, d, 'China')
p2 = DomesticProduct("Buoi", "Trai Cay", 18000, d)
p3 = ImportedProduct("Man", "Trai Cay", 100000, d, 'America')
p4 = DomesticProduct("Mit", "Trai Cay", 400, d)
p5 = DomesticProduct("Xoai", "Trai Cay", 10000, d)

od_item1 = OrderItem(p1, 2)
od_item2 = OrderItem(p2, 5)
od_item3 = OrderItem(p3, 1)
od_item4 = OrderItem(p4, 7)
od_item5 = OrderItem(p5, 3)
od_item6 = OrderItem(p3, 1)
od_item7 = OrderItem(p2, 2)

o1 = Order(1, 'Nhu', 'Phung', date, [od_item1, od_item2, od_item4])
o2 = Order(2, 'Nhu', 'Phung', date, [od_item4, od_item1])
o3 = Order(3, 'Nhu', 'Phung', date, [od_item6, od_item7, od_item5])

om1 = OrderManager([o1, o2, o3])

print('Product highest price is', om1.getProductHighestPriceInOders())
print('Number of products bought by each type of product \n', om1.showNumberOfProducts())


Product highest price is Man 100000 America
Number of products bought by each type of product 
 {Xoai 10000 China: 4, Buoi 18000: 7, Mit 400: 14, Man 100000 America: 1, Xoai 10000: 3}


Task 2.1. Develop a NumPy program to create an array with values ranging from 10 to 25, then reverse the array (the first element becomes last).

In [2]:
import numpy as np
array = np.arange(10, 26, 1)
print(array)
array = array[::-1]
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]
[25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


Task 2.2. Develop a NumPy program that constructs an array by repeating. 

In [3]:
array = np.arange(1, 5, 1)
print(np.tile(array, 3))

[1 2 3 4 1 2 3 4 1 2 3 4]


Task 2.3. Develop a NumPy program to replace all elements of NumPy array that are greater
than a specified array.

In [8]:
x = np.array([[0.42, 0.48, 0.32], [0.74, 0.58, 0.38], [0.5, 0.34, 0.15]])
print(x)
print('-------------------')
x[x > .5] = .5
print(x)

[[0.42 0.48 0.32]
 [0.74 0.58 0.38]
 [0.5  0.34 0.15]]
-------------------
[[0.42 0.48 0.32]
 [0.5  0.5  0.38]
 [0.5  0.34 0.15]]
